# ──────────────────────────────────────────────────
# Link        https://www.hackerrank.com/challenges/designer-door-mat/problem?isFullScreen=true
# Problem     Designer Door Mat
# Difficulty  Easy
# Subdomain   Strings
# Platform    HackerRank
# Language    python3
# Status      Accepted
# Submitted   2026-08-20, 03:30 p.m.
# Technique   string-formatting-center-method
# Time        O(N^2)
# Space       O(N)
# Insight     The pattern is generated by iterating through rows using the center method to pad strings with hyphens based on the input dimensions.
# Interview   Before: "How would you construct this symmetric pattern?" After: "I used the center method to pad the pattern strings with hyphens, resulting in O(N^2) time complexity because each of the N rows requires O(M) string construction where M is 3N."
# Pitfalls    (1) Incorrectly calculating the number of rows as N instead of N//2 for the top and bottom sections.  (2) Failing to account for the M = 3N constraint when using the center method for padding.  (3) Using an incorrect range for the bottom loop, which must exclude the middle WELCOME row.
# ──────────────────────────────────────────────────

N,M = map(int,input().split())

for i in range(N//2):
    pattern = ".|."*(2*i+1)
    print(pattern.center(M,"-"))
    
print("WELCOME".center(M,"-"))

for i in range(N//2-1,-1,-1):
    pattern = ".|."*(2*i+1)
    print(pattern.center(M,"-"))
